language: python
cache: pip3
python:
- '3.6'
sudo: required
matrix:
  fast_finish: true
install:
  - pip3 install awscli==1.16.190

before_script:
  - nvm use v11.0.0
  - npm install -g serverless
  - chmod +x ./scripts/set_env.sh && source ./scripts/set_env.sh
  - chmod +x ./deploy.sh
  - pip3 install alembic==1.2.1
  - pip3 install PyMySQL==0.9.3
  - pip3 install SQLAlchemy==1.3.8
  - pip3 install SQLAlchemy-Utils==0.34.2
  - pip3 install graphene==2.1.8

script:
- set -e
- make test DB_HOST=localhost
- ./deploy.sh
