"""remove_payment

Revision ID: 02a6749d6d9f
Revises: 7848cedd0ab3
Create Date: 2019-10-22 19:06:23.553656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02a6749d6d9f'
down_revision = '7848cedd0ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_terms', 'payment_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_terms', sa.Column('payment_type', mysql.ENUM('BOLETO', 'CARTAO_CREDITO', 'DINHEIRO'), nullable=True))
    # ### end Alembic commands ###
