"""sku_unique

Revision ID: 0642638364b6
Revises: 534366eacb46
Create Date: 2019-10-11 00:15:48.067491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0642638364b6'
down_revision = '534366eacb46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_seller_id_sku', 'product', ['seller_id', 'sku'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_seller_id_sku', 'product', type_='unique')
    # ### end Alembic commands ###
