"""update_orders

Revision ID: 0d17252244a3
Revises: b54b6ad6253d
Create Date: 2019-10-18 13:02:34.334826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d17252244a3'
down_revision = 'b54b6ad6253d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_ibfk_3', 'order', type_='foreignkey')
    op.drop_column('order', 'payment_id')
    op.add_column('order_payment', sa.Column('order_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order_payment', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_payment', type_='foreignkey')
    op.drop_column('order_payment', 'order_id')
    op.add_column('order', sa.Column('payment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('order_ibfk_3', 'order', 'order_payment', ['payment_id'], ['id'])
    # ### end Alembic commands ###
