"""status

Revision ID: 0f2c1dee2cd6
Revises: f55a02268205
Create Date: 2019-10-16 08:09:07.787232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2c1dee2cd6'
down_revision = 'f55a02268205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_status', sa.Column('status', sa.Enum('NEW', 'APPROVED', 'INVOICED', 'SHIPPED', 'DELIVERED', 'CANCELED', 'SHIPMENT_EXCEPTION', 'PAYMENT_OVERDUE', name='orderstatustype'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_status', 'status')
    # ### end Alembic commands ###
