"""order_item_sku_quantity

Revision ID: 2072f23d854e
Revises: 40a35e8b296a
Create Date: 2020-03-17 12:06:44.002791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2072f23d854e'
down_revision = '40a35e8b296a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_order_id_sku', 'order_item', ['order_id', 'sku'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_order_id_sku_quantity', 'order_item', type_='unique')
    # ### end Alembic commands ###
