"""document_unique

Revision ID: 28d6dc996c76
Revises: cbaee6f8a54e
Create Date: 2019-10-18 17:09:04.520931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28d6dc996c76'
down_revision = 'cbaee6f8a54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_seller_id_document', 'customer', ['seller_id', 'document'])
    op.alter_column('order', 'delivery_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('order', 'order_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'order_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('order', 'delivery_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_constraint('_seller_id_document', 'customer', type_='unique')
    # ### end Alembic commands ###
