"""add_default_owner_on_status

Revision ID: 2d4985e43167
Revises: e86c1f629d60
Create Date: 2020-08-31 13:48:03.044967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
from menu_sun_api.domain.model.order.order import OwnerType

revision = '2d4985e43167'
down_revision = 'e86c1f629d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_status', 'owner',
                    type_=sa.Enum('MENU', 'SELLER', name='ownertype'),
                    server_default='SELLER')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_status', 'owner',
                    type_=sa.Enum('MENU', 'SELLER', name='ownertype'),
                    existing_nullable=False)
    # ### end Alembic commands ###
