"""unique_pricing

Revision ID: 2f1573b04fda
Revises: 57f0657e075d
Create Date: 2019-11-04 16:07:08.506618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f1573b04fda'
down_revision = '57f0657e075d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_customer_id_product_id', 'pricing', ['customer_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_customer_id_product_id', 'pricing', type_='unique')
    # ### end Alembic commands ###
