"""remove_metafield

Revision ID: 362eb9c77442
Revises: 903f578cf8de
Create Date: 2019-10-21 23:39:03.575221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '362eb9c77442'
down_revision = '903f578cf8de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_metafield', 'value')
    op.drop_column('order_metafield', 'value')
    op.drop_column('product_metafield', 'value')
    op.drop_column('seller_metafield', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_metafield', sa.Column('value', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('product_metafield', sa.Column('value', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('order_metafield', sa.Column('value', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('customer_metafield', sa.Column('value', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
