"""add_brf_option_into_integration_type

Revision ID: 3cb9de2dd95a
Revises: e25728d6df7c
Create Date: 2020-05-13 16:59:29.544249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3cb9de2dd95a'
down_revision = 'e25728d6df7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller', 'integration_type',
                    existing_type=mysql.ENUM('NONE', 'PROMAX'),
                    type_=sa.Enum('NOT_IMPLEMENTED', 'PROMAX', 'PERNOD', 'BRF', name='integrationtype'),
                    existing_nullable=False,
                    existing_server_default=sa.text("'NOT_IMPLEMENTED'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller', 'integration_type',
                    existing_type=sa.Enum('NOT_IMPLEMENTED', 'PROMAX', 'PERNOD', name='integrationtype'),
                    type_=mysql.ENUM('NONE', 'PROMAX'),
                    existing_nullable=False,
                    existing_server_default=sa.text("'NOT_IMPLEMENTED'"))
    # ### end Alembic commands ###
