"""publish_date

Revision ID: 40a35e8b296a
Revises: 871a34e2b0c5
Create Date: 2019-11-10 16:12:19.640995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40a35e8b296a'
down_revision = '871a34e2b0c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_status', sa.Column('published_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_status', 'published_date')
    # ### end Alembic commands ###
