"""order_queue_date

Revision ID: 42be5da0f0fb
Revises: da75318a70bd
Create Date: 2019-10-18 08:02:23.217193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42be5da0f0fb'
down_revision = 'da75318a70bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_queue_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'order_queue_date')
    # ### end Alembic commands ###
