"""adding_index_for_sku_field_on_product

Revision ID: 460f067a4856
Revises: 768263ad33ca
Create Date: 2020-07-07 16:55:18.240676

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '460f067a4856'
down_revision = '2fc4c18f1104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer', 'active',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               nullable=True)
    op.alter_column('order', 'commissioned',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=False)
    op.create_index(op.f('ix_product_sku'), 'product', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_sku'), table_name='product')
    op.alter_column('order', 'commissioned',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=False)
    op.alter_column('customer', 'active',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###
