"""recreate_metafield

Revision ID: 4de9558e4a5b
Revises: 6a222686c9b3
Create Date: 2019-10-18 15:24:12.786562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4de9558e4a5b'
down_revision = '6a222686c9b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_metafield', sa.Column('customer_id', sa.Integer(), nullable=False))
    op.drop_constraint('customer_metafield_ibfk_1', 'customer_metafield', type_='foreignkey')
    op.create_foreign_key(None, 'customer_metafield', 'customer', ['customer_id'], ['id'])
    op.drop_column('customer_metafield', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_metafield', sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customer_metafield', type_='foreignkey')
    op.create_foreign_key('customer_metafield_ibfk_1', 'customer_metafield', 'customer', ['order_id'], ['id'])
    op.drop_column('customer_metafield', 'customer_id')
    # ### end Alembic commands ###
