"""product_metadata

Revision ID: 534366eacb46
Revises: db9b4cc35eec
Create Date: 2019-10-10 12:38:13.870036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '534366eacb46'
down_revision = 'db9b4cc35eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_tags',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('keyword', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('brand', sa.String(length=256), nullable=True))
    op.add_column('product', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('ean', sa.String(length=16), nullable=True))
    op.add_column('product', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('length', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('name', sa.String(length=256), nullable=True))
    op.add_column('product', sa.Column('ncm', sa.String(length=16), nullable=True))
    op.add_column('product', sa.Column('product_metadata', sa.BLOB(), nullable=True))
    op.add_column('product', sa.Column('status', sa.Enum('ENABLED', 'DISABLED', name='productstatus'), nullable=True))
    op.add_column('product', sa.Column('weight', sa.Float(), nullable=True))
    op.add_column('product', sa.Column('width', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'width')
    op.drop_column('product', 'weight')
    op.drop_column('product', 'status')
    op.drop_column('product', 'product_metadata')
    op.drop_column('product', 'ncm')
    op.drop_column('product', 'name')
    op.drop_column('product', 'length')
    op.drop_column('product', 'height')
    op.drop_column('product', 'ean')
    op.drop_column('product', 'cost')
    op.drop_column('product', 'brand')
    op.drop_table('meta_tags')
    # ### end Alembic commands ###
