"""bulk

Revision ID: 57f0657e075d
Revises: 5c6128084f3e
Create Date: 2019-11-04 01:56:28.623590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f0657e075d'
down_revision = '5c6128084f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_bulkload',
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('document', sa.String(length=16), nullable=False),
    sa.Column('list_price', sa.Float(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('sku', 'document')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pricing_bulkload')
    # ### end Alembic commands ###
