"""price_required

Revision ID: 5c6128084f3e
Revises: d2be8fdf8e83
Create Date: 2019-10-28 16:55:00.928945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c6128084f3e'
down_revision = 'd2be8fdf8e83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customer_metafield', 'key',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('customer_metafield', 'namespace',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('order_item', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('order_metafield', 'key',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('order_metafield', 'namespace',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('product_metafield', 'key',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('product_metafield', 'namespace',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('seller_metafield', 'key',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('seller_metafield', 'namespace',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller_metafield', 'namespace',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('seller_metafield', 'key',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('product_metafield', 'namespace',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('product_metafield', 'key',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('order_metafield', 'namespace',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('order_metafield', 'key',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('order_item', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('customer_metafield', 'namespace',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('customer_metafield', 'key',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
