"""remove_metafield

Revision ID: 6888ba16fce9
Revises: 05eff8379912
Create Date: 2019-10-18 15:15:50.953960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6888ba16fce9'
down_revision = '05eff8379912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_metafield', sa.Column('order_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'order_metafield', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_metafield', type_='foreignkey')
    op.drop_column('order_metafield', 'order_id')
    # ### end Alembic commands ###
