"""customer_Name

Revision ID: 6d52fbeb81bd
Revises: 0642638364b6
Create Date: 2019-10-11 18:31:06.708470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d52fbeb81bd'
down_revision = '0642638364b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('name', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'name')
    # ### end Alembic commands ###
