"""addin_new_migration_pending_review

Revision ID: 768263ad33ca
Revises: 9f75358360fc
Create Date: 2020-06-12 14:41:49.329434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '768263ad33ca'
down_revision = '429e298c85f2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_status', 'status',
                    existing_type=mysql.ENUM('NEW', 'APPROVED', 'INVOICED', 'SHIPPED', 'DELIVERED',
                                             'SHIPMENT_EXCEPTION', 'PAYMENT_OVERDUE',
                                             'NEW_ORDER',
                                             'SELLER_REVIEW',
                                             'PROCESSING',
                                             'ORDER_INVOICED',
                                             'PENDING',
                                             'CANCELED',
                                             'CREDIT_MENU',
                                             'CLOSED'),
                    type_=sa.Enum('NEW', 'APPROVED', 'INVOICED', 'SHIPPED', 'DELIVERED',
                                  'SHIPMENT_EXCEPTION', 'PAYMENT_OVERDUE',
                                  'NEW_ORDER',
                                  'SELLER_REVIEW',
                                  'PROCESSING',
                                  'ORDER_INVOICED',
                                  'PENDING',
                                  'CANCELED',
                                  'CREDIT_MENU',
                                  'CLOSED', 'PENDING_REVIEW', name='status'),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_status', 'status',
                    existing_type=sa.Enum('NEW', 'APPROVED', 'INVOICED', 'SHIPPED', 'DELIVERED',
                                          'SHIPMENT_EXCEPTION', 'PAYMENT_OVERDUE',
                                          'NEW_ORDER',
                                          'SELLER_REVIEW',
                                          'PROCESSING',
                                          'ORDER_INVOICED',
                                          'PENDING',
                                          'CANCELED',
                                          'CREDIT_MENU',
                                          'CLOSED', 'PENDING_REVIEW', name='status'),
                    type_=mysql.ENUM('NEW', 'APPROVED', 'INVOICED', 'SHIPPED', 'DELIVERED',
                                     'SHIPMENT_EXCEPTION', 'PAYMENT_OVERDUE',
                                     'NEW_ORDER',
                                     'SELLER_REVIEW',
                                     'PROCESSING',
                                     'ORDER_INVOICED',
                                     'PENDING',
                                     'CANCELED',
                                     'CREDIT_MENU',
                                     'CLOSED'),
                    existing_nullable=False)
    # ### end Alembic commands ###

