"""metafields

Revision ID: 7ad75d10ec49
Revises: 1c6ea458f448
Create Date: 2019-10-17 16:56:12.657013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad75d10ec49'
down_revision = '1c6ea458f448'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metafield', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'metafield', 'product', ['product_id'], ['id'])
    op.drop_column('product', 'product_metadata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_metadata', sa.BLOB(), nullable=True))
    op.drop_constraint(None, 'metafield', type_='foreignkey')
    op.drop_column('metafield', 'product_id')
    # ### end Alembic commands ###
