"""add_active_property_on_customer

Revision ID: 7bbdc8a9d923
Revises: 3cb9de2dd95a
Create Date: 2020-05-14 08:51:23.727617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bbdc8a9d923'
down_revision = '3cb9de2dd95a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'active')
    # ### end Alembic commands ###
