"""order_delete_cascade

Revision ID: 871a34e2b0c5
Revises: 2f1573b04fda
Create Date: 2019-11-10 11:50:25.450187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '871a34e2b0c5'
down_revision = '2f1573b04fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_item_ibfk_1', 'order_item', type_='foreignkey')
    op.create_foreign_key(None, 'order_item', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('order_metafield_ibfk_1', 'order_metafield', type_='foreignkey')
    op.create_foreign_key(None, 'order_metafield', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('order_payment_ibfk_1', 'order_payment', type_='foreignkey')
    op.create_foreign_key(None, 'order_payment', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('order_status_ibfk_1', 'order_status', type_='foreignkey')
    op.create_foreign_key(None, 'order_status', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_status', type_='foreignkey')
    op.create_foreign_key('order_status_ibfk_1', 'order_status', 'order', ['order_id'], ['id'])
    op.drop_constraint(None, 'order_payment', type_='foreignkey')
    op.create_foreign_key('order_payment_ibfk_1', 'order_payment', 'order', ['order_id'], ['id'])
    op.drop_constraint(None, 'order_metafield', type_='foreignkey')
    op.create_foreign_key('order_metafield_ibfk_1', 'order_metafield', 'order', ['order_id'], ['id'])
    op.drop_constraint(None, 'order_item', type_='foreignkey')
    op.create_foreign_key('order_item_ibfk_1', 'order_item', 'order', ['order_id'], ['id'])
    # ### end Alembic commands ###
