"""adding_pending_invoice_completed_and_entregue_status

Revision ID: a4543ba2db7a
Revises: 345d9a97deb4
Create Date: 2020-08-24 12:04:21.073925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4543ba2db7a'
down_revision = '345d9a97deb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_status', 'status',
                    existing_type=mysql.ENUM('NEW', 'APPROVED', 'INVOICED', 'SHIPPED', 'DELIVERED',
                                             'SHIPMENT_EXCEPTION', 'PAYMENT_OVERDUE',
                                             'NEW_ORDER',
                                             'SELLER_REVIEW',
                                             'PROCESSING',
                                             'ORDER_INVOICED',
                                             'PENDING',
                                             'CANCELED',
                                             'CREDIT_MENU',
                                             'CLOSED', 'PENDING_REVIEW'),
                    type_=sa.Enum('NEW', 'APPROVED', 'INVOICED', 'SHIPPED', 'DELIVERED',
                                  'SHIPMENT_EXCEPTION', 'PAYMENT_OVERDUE',
                                  'NEW_ORDER',
                                  'SELLER_REVIEW',
                                  'PROCESSING',
                                  'ORDER_INVOICED',
                                  'PENDING',
                                  'CANCELED',
                                  'CREDIT_MENU',
                                  'CLOSED', 'PENDING_REVIEW', 'PENDING_INVOICE', 'ENTREGUE', 'COMPLETE', name='status'),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_status', 'status',
                    existing_type=sa.Enum('NEW', 'APPROVED', 'INVOICED', 'SHIPPED', 'DELIVERED',
                                          'SHIPMENT_EXCEPTION', 'PAYMENT_OVERDUE',
                                          'NEW_ORDER',
                                          'SELLER_REVIEW',
                                          'PROCESSING',
                                          'ORDER_INVOICED',
                                          'PENDING',
                                          'CANCELED',
                                          'CREDIT_MENU',
                                          'CLOSED', 'PENDING_REVIEW', 'PENDING_INVOICE', 'ENTREGUE', 'COMPLETE',
                                          name='status'),
                    type_=mysql.ENUM('NEW', 'APPROVED', 'INVOICED', 'SHIPPED', 'DELIVERED',
                                     'SHIPMENT_EXCEPTION', 'PAYMENT_OVERDUE',
                                     'NEW_ORDER',
                                     'SELLER_REVIEW',
                                     'PROCESSING',
                                     'ORDER_INVOICED',
                                     'PENDING',
                                     'CANCELED',
                                     'CREDIT_MENU',
                                     'CLOSED', 'PENDING_REVIEW'),
                    existing_nullable=False)
# ### end Alembic commands ###
