"""recreate_metafield

Revision ID: ad676230dd2e
Revises: 362eb9c77442
Create Date: 2019-10-21 23:39:28.365248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad676230dd2e'
down_revision = '362eb9c77442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_metafield', sa.Column('value', mysql.LONGTEXT(), nullable=True))
    op.add_column('order_metafield', sa.Column('value', mysql.LONGTEXT(), nullable=True))
    op.add_column('product_metafield', sa.Column('value', mysql.LONGTEXT(), nullable=True))
    op.add_column('seller_metafield', sa.Column('value', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_metafield', 'value')
    op.drop_column('product_metafield', 'value')
    op.drop_column('order_metafield', 'value')
    op.drop_column('customer_metafield', 'value')
    # ### end Alembic commands ###
