"""update_orders

Revision ID: b54b6ad6253d
Revises: 5f225fc7c36f
Create Date: 2019-10-18 12:48:34.101275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b54b6ad6253d'
down_revision = '5f225fc7c36f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('shipping', sa.Float(), nullable=False))
    op.add_column('order', sa.Column('subtotal', sa.Float(), nullable=False))
    op.add_column('order', sa.Column('total', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'total')
    op.drop_column('order', 'subtotal')
    op.drop_column('order', 'shipping')
    op.drop_column('order', 'discount')
    # ### end Alembic commands ###
