"""recreate_metafield

Revision ID: cbaee6f8a54e
Revises: 4de9558e4a5b
Create Date: 2019-10-18 15:24:41.174433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbaee6f8a54e'
down_revision = '4de9558e4a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_metafield', sa.Column('product_id', sa.Integer(), nullable=False))
    op.drop_constraint('product_metafield_ibfk_1', 'product_metafield', type_='foreignkey')
    op.create_foreign_key(None, 'product_metafield', 'product', ['product_id'], ['id'])
    op.drop_column('product_metafield', 'order_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_metafield', sa.Column('order_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'product_metafield', type_='foreignkey')
    op.create_foreign_key('product_metafield_ibfk_1', 'product_metafield', 'product', ['order_id'], ['id'])
    op.drop_column('product_metafield', 'product_id')
    # ### end Alembic commands ###
