"""add_new_payment

Revision ID: d2be8fdf8e83
Revises: 02a6749d6d9f
Create Date: 2019-10-22 19:06:55.002228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2be8fdf8e83'
down_revision = '02a6749d6d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_terms', sa.Column('payment_type', sa.Enum('BOLETO', 'CARTAO_CREDITO', 'DINHEIRO', 'CHEQUE', name='paymenttype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_terms', 'payment_type')
    # ### end Alembic commands ###
