"""payment_terms

Revision ID: db9b4cc35eec
Revises: 53ed3c2c2e14
Create Date: 2019-10-09 22:26:32.754405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9b4cc35eec'
down_revision = '53ed3c2c2e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_terms', sa.Column('description', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_terms', 'description')
    # ### end Alembic commands ###
