"""order

Revision ID: de31ffd8a769
Revises: 6d52fbeb81bd
Create Date: 2019-10-14 13:29:18.218813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de31ffd8a769'
down_revision = '6d52fbeb81bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_billing_address',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=512), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('complement', sa.String(length=64), nullable=True),
    sa.Column('reference', sa.String(length=512), nullable=True),
    sa.Column('neighborhood', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('secondary_phone', sa.String(length=16), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_customer',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_payment',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_shipping_address',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street', sa.String(length=512), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('complement', sa.String(length=64), nullable=True),
    sa.Column('reference', sa.String(length=512), nullable=True),
    sa.Column('neighborhood', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=True),
    sa.Column('secondary_phone', sa.String(length=16), nullable=True),
    sa.Column('postcode', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('shipping_address_id', sa.Integer(), nullable=False),
    sa.Column('billing_address_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['billing_address_id'], ['order_billing_address.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['order_payment.id'], ),
    sa.ForeignKeyConstraint(['shipping_address_id'], ['order_shipping_address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('ean', sa.String(length=16), nullable=True),
    sa.Column('ncm', sa.String(length=16), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('original_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_status',
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('comments', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_status')
    op.drop_table('order_item')
    op.drop_table('order')
    op.drop_table('order_shipping_address')
    op.drop_table('order_payment')
    op.drop_table('order_customer')
    op.drop_table('order_billing_address')
    # ### end Alembic commands ###
