"""add_pernod_option_into_integration_type_enum

Revision ID: e25728d6df7c
Revises: e69fe0b15914
Create Date: 2020-04-29 09:40:07.709313

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e25728d6df7c'
down_revision = 'e69fe0b15914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller', 'integration_type',
                    existing_type=mysql.ENUM('NONE', 'PROMAX'),
                    type_=sa.Enum('NOT_IMPLEMENTED', 'PROMAX', 'PERNOD', name='status'),
                    existing_nullable=False,
                    existing_server_default=sa.text("'NOT_IMPLEMENTED'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('seller', 'integration_type',
                    existing_type=sa.Enum('NOT_IMPLEMENTED', 'PROMAX', 'PERNOD', name='status'),
                    type_=mysql.ENUM('NONE', 'PROMAX'),
                    existing_nullable=False,
                    existing_server_default=sa.text("'NOT_IMPLEMENTED'"))
    # ### end Alembic commands ###
