"""add_field_integration_type_into_seller

Revision ID: e69fe0b15914
Revises: 2072f23d854e
Create Date: 2020-04-09 22:26:34.547705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e69fe0b15914'
down_revision = '2072f23d854e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_order_id_sku_quantity', 'order_item', ['order_id', 'sku', 'quantity'])
    op.drop_index('_order_id_sku', table_name='order_item')
    op.add_column('seller', sa.Column('integration_type', sa.Enum('NONE', 'PROMAX', name='integrationtype'), server_default='NONE', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller', 'integration_type')
    op.create_index('_order_id_sku', 'order_item', ['order_id', 'sku'], unique=True)
    op.drop_constraint('_order_id_sku_quantity', 'order_item', type_='unique')
    # ### end Alembic commands ###
