"""add_order_refunded

Revision ID: e86c1f629d60
Revises: 52e1c085c21e
Create Date: 2020-08-27 17:29:51.558667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e86c1f629d60'
down_revision = '52e1c085c21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_status', 'status',
                    existing_type=mysql.ENUM('NEW', 'APPROVED', 'INVOICED', 'SHIPPED', 'DELIVERED',
                                             'SHIPMENT_EXCEPTION', 'PAYMENT_OVERDUE',
                                             'NEW_ORDER',
                                             'SELLER_REVIEW',
                                             'PROCESSING',
                                             'ORDER_INVOICED',
                                             'PENDING',
                                             'CANCELED',
                                             'CREDIT_MENU',
                                             'CLOSED', 'PENDING_REVIEW', 'PENDING_INVOICE', 'ENTREGUE', 'COMPLETE'),
                    type_=sa.Enum('NEW', 'APPROVED', 'INVOICED', 'SHIPPED', 'DELIVERED',
                                  'SHIPMENT_EXCEPTION', 'PAYMENT_OVERDUE',
                                  'NEW_ORDER',
                                  'SELLER_REVIEW',
                                  'PROCESSING',
                                  'ORDER_INVOICED',
                                  'PENDING',
                                  'CANCELED',
                                  'CREDIT_MENU',
                                  'CLOSED', 'PENDING_REVIEW', 'PENDING_INVOICE', 'ENTREGUE', 'COMPLETE',
                                  'ORDER_REFUNDED', name='status'),
                    existing_nullable=False)


# ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_status', 'status',
                    existing_type=sa.Enum('NEW', 'APPROVED', 'INVOICED', 'SHIPPED', 'DELIVERED',
                                          'SHIPMENT_EXCEPTION', 'PAYMENT_OVERDUE',
                                          'NEW_ORDER',
                                          'SELLER_REVIEW',
                                          'PROCESSING',
                                          'ORDER_INVOICED',
                                          'PENDING',
                                          'CANCELED',
                                          'CREDIT_MENU',
                                          'CLOSED', 'PENDING_REVIEW', 'PENDING_INVOICE', 'ENTREGUE', 'COMPLETE',
                                          'ORDER_REFUNDED', name='status'),
                    type_=mysql.ENUM('NEW', 'APPROVED', 'INVOICED', 'SHIPPED', 'DELIVERED',
                                     'SHIPMENT_EXCEPTION', 'PAYMENT_OVERDUE',
                                     'NEW_ORDER',
                                     'SELLER_REVIEW',
                                     'PROCESSING',
                                     'ORDER_INVOICED',
                                     'PENDING',
                                     'CANCELED',
                                     'CREDIT_MENU',
                                     'CLOSED', 'PENDING_REVIEW', 'PENDING_INVOICE', 'ENTREGUE', 'COMPLETE'),
                    existing_nullable=False)
    # ### end Alembic commands ###
