"""namespace

Revision ID: f43523fb0177
Revises: ad676230dd2e
Create Date: 2019-10-21 23:50:51.545553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43523fb0177'
down_revision = 'ad676230dd2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_metafield', sa.Column('namespace', sa.String(length=64), nullable=True))
    op.add_column('order_metafield', sa.Column('namespace', sa.String(length=64), nullable=True))
    op.add_column('product_metafield', sa.Column('namespace', sa.String(length=64), nullable=True))
    op.add_column('seller_metafield', sa.Column('namespace', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_metafield', 'namespace')
    op.drop_column('product_metafield', 'namespace')
    op.drop_column('order_metafield', 'namespace')
    op.drop_column('customer_metafield', 'namespace')
    # ### end Alembic commands ###
