"""add_seller_id

Revision ID: f55a02268205
Revises: c1418755dcbb
Create Date: 2019-10-15 18:04:26.308912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f55a02268205'
down_revision = 'c1418755dcbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_id', sa.String(length=32), nullable=False))
    op.add_column('order', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.add_column('order', sa.Column('seller_order_id', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 'order', 'seller', ['seller_id'], ['id'])
    op.drop_column('order_item', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'seller_order_id')
    op.drop_column('order', 'seller_id')
    op.drop_column('order', 'order_id')
    # ### end Alembic commands ###
