#!/usr/bin/env bash
set_prod_environment()
{
    echo "Setting [PROD] variables"
    export ENVIRONMENT=prod
    export AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID
    export AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY
    export BASTION_IP=$PROD_BASTION_IP
    export DB_HOST=$PROD_DB_HOST
    export DB_PASSWORD=$PROD_DB_PASSWORD
    export DB_PORT=$PROD_DB_PORT
    export DB_USER=$PROD_DB_USER
    export DB_NAME=sun_db
    export BASTION_PRIVATE_KEY=bastion_rsa.prod
    export BASTION_USER=deploy
    export ORDER_STATUS_WEBHOOK=$PROD_ORDER_STATUS_WEBHOOK
    export BEARER_TOKEN=$PROD_BEARER_TOKEN
    export STAGE=prod
    export SUBNET_A=$PROD_SUBNET_A
    export SUBNET_B=$PROD_SUBNET_B
    export LAMBDA_SECURITY_GROUP=$PROD_LAMBDA_SECURITY_GROUP
    export ORDER_QUEUE_URL=$PROD_ORDER_QUEUE_URL
    export INVENTORY_QUEUE_URL=$PROD_INVENTORY_QUEUE_URL
    export PRODUCT_QUEUE_URL=$PROD_PRODUCT_QUEUE_URL
    export CUSTOMER_QUEUE_URL=$PROD_CUSTOMER_QUEUE_URL
    export PRICING_QUEUE_URL=$PROD_PRICING_QUEUE_URL
    export INVENTORY_BY_SKU_QUEUE_URL=$PROD_INVENTORY_BY_SKU_QUEUE_URL
    export PRICING_BY_SKU_QUEUE_URL=$PROD_PRICING_BY_SKU_QUEUE_URL
    export DEFAULT_PRICING_QUEUE_URL=$PROD_DEFAULT_PRICING_QUEUE_URL
    export PROMAX_PASSWORD=$PROD_PROMAX_PASSWORD
    export PROMAX_USER_ID=$PROD_PROMAX_USER_ID
    export PROMAX_IP=$PROD_PROMAX_IP
    export PERNOD_API_URL=$PROD_PERNOD_API_URL
    export PERNOD_CLIENT_ID=$PROD_PERNOD_CLIENT_ID
    export PERNOD_CLIENT_SECRET=$PROD_PERNOD_CLIENT_SECRET
    export PERNOD_MENU_USERNAME=$PROD_PERNOD_MENU_USERNAME
    export PERNOD_MENU_PASSWORD=$PROD_PERNOD_MENU_PASSWORD
    export PERNOD_PRODUCT_API_URL=$PROD_PERNOD_PRODUCT_API_URL
    export PERNOD_PRODUCT_API_TOKEN=$PROD_PERNOD_PRODUCT_API_TOKEN
    export PERNOD_PRODUCT_API_PAGE_SIZE=$PROD_PERNOD_PRODUCT_API_PAGE_SIZE
    export PERNOD_ID_TENANT=$PROD_PERNOD_ID_TENANT
    export BRF_API_URL=$PROD_BRF_API_URL
    export BRF_API_KEY=$PROD_BRF_API_KEY
    export SERBOM_TOKEN=$PROD_SERBOM_TOKEN
    export URL_SEPARATION_SERBOM=$PROD_URL_SEPARATION_SERBOM
    export SOAPACTION_SERBOM=$PROD_SOAPACTION_SERBOM
    export DOCUMENT_ARYZTA=$PROD_DOCUMENT_ARYZTA
    export DOCUMENT_BENJAMIN=$PROD_DOCUMENT_BENJAMIN
    export ARYZTA_BUCKET=$PROD_ARYZTA_BUCKET
    export BENJAMIN_BUCKET=$PROD_BENJAMIN_BUCKET
    export ORDER_STATUS_QUEUE_URL=$PROD_ORDER_STATUS_QUEUE_URL
    export ORDER_STATUS_NOTIFICATION_QUEUE_URL=$PROD_ORDER_STATUS_NOTIFICATION_QUEUE_URL

}
set_dev_environment()
{
    echo "Setting [DEV] variables"
    export ENVIRONMENT=dev
    export AWS_ACCESS_KEY_ID=$DEV_AWS_ACCESS_KEY_ID
    export AWS_SECRET_ACCESS_KEY=$DEV_AWS_SECRET_ACCESS_KEY
    export BASTION_IP=$DEV_BASTION_IP
    export DB_HOST=$DEV_DB_HOST
    export DB_PASSWORD=$DEV_DB_PASSWORD
    export DB_PORT=$DEV_DB_PORT
    export DB_USER=$DEV_DB_USER
    export DB_NAME=${TRAVIS_BRANCH//[\/-]/_}
    export BASTION_PRIVATE_KEY=bastion_rsa.dev
    export BASTION_USER=deploy-user
    export ORDER_STATUS_WEBHOOK=$DEV_ORDER_STATUS_WEBHOOK
    export BEARER_TOKEN=$DEV_BEARER_TOKEN
    export STAGE=$TRAVIS_BRANCH
    export SUBNET_A=$DEV_SUBNET_A
    export SUBNET_B=$DEV_SUBNET_B
    export LAMBDA_SECURITY_GROUP=$DEV_LAMBDA_SECURITY_GROUP
    export ORDER_QUEUE_URL=$DEV_ORDER_QUEUE_URL
    export INVENTORY_BY_SKU_QUEUE_URL=$DEV_INVENTORY_BY_SKU_QUEUE_URL
    export PRICING_BY_SKU_QUEUE_URL=$DEV_PRICING_BY_SKU_QUEUE_URL
    export DEFAULT_PRICING_QUEUE_URL=$DEV_DEFAULT_PRICING_QUEUE_URL
    export INVENTORY_QUEUE_URL=$DEV_INVENTORY_QUEUE_URL
    export PRODUCT_QUEUE_URL=$DEV_PRODUCT_QUEUE_URL
    export CUSTOMER_QUEUE_URL=$DEV_CUSTOMER_QUEUE_URL
    export PRICING_QUEUE_URL=$DEV_PRICING_QUEUE_URL
    export PROMAX_PASSWORD=$DEV_PROMAX_PASSWORD
    export PROMAX_USER_ID=$DEV_PROMAX_USER_ID
    export PROMAX_IP=$DEV_PROMAX_IP
    export PERNOD_API_URL=$DEV_PERNOD_API_URL
    export PERNOD_CLIENT_ID=$DEV_PERNOD_CLIENT_ID
    export PERNOD_CLIENT_SECRET=$DEV_PERNOD_CLIENT_SECRET
    export PERNOD_MENU_USERNAME=$DEV_PERNOD_MENU_USERNAME
    export PERNOD_MENU_PASSWORD=$DEV_PERNOD_MENU_PASSWORD
    export PERNOD_PRODUCT_API_URL=$DEV_PERNOD_PRODUCT_API_URL
    export PERNOD_PRODUCT_API_TOKEN=$DEV_PERNOD_PRODUCT_API_TOKEN
    export PERNOD_PRODUCT_API_PAGE_SIZE=$DEV_PERNOD_PRODUCT_API_PAGE_SIZE
    export PERNOD_ID_TENANT=$DEV_PERNOD_ID_TENANT
    export BRF_API_URL=$DEV_BRF_API_URL
    export BRF_API_KEY=$DEV_BRF_API_KEY
    export SERBOM_TOKEN=$DEV_SERBOM_TOKEN
    export URL_SEPARATION_SERBOM=$DEV_URL_SEPARATION_SERBOM
    export SOAPACTION_SERBOM=$DEV_SOAPACTION_SERBOM
    export DOCUMENT_ARYZTA=$DEV_DOCUMENT_ARYZTA
    export DOCUMENT_BENJAMIN=$DEV_DOCUMENT_BENJAMIN
    export ARYZTA_BUCKET=$DEV_ARYZTA_BUCKET
    export BENJAMIN_BUCKET=$DEV_BENJAMIN_BUCKET
    export ORDER_STATUS_QUEUE_URL=$DEV_ORDER_STATUS_QUEUE_URL
    export ORDER_STATUS_NOTIFICATION_QUEUE_URL=$DEV_ORDER_STATUS_NOTIFICATION_QUEUE_URL

}
if [ "$TRAVIS_BRANCH" == "master" ]; then
    set_prod_environment
else
    set_dev_environment
fi
